# The kitty terminal template for wallust
# Add to wallust config: kitty = { src='kitty.conf', dst='~/.config/kitty/colors.conf'}
# And add to kitty config: include colors.conf

cursor #9D9D9E

background #1E1E20
foreground #F4F4F4

color0 #4A4A4B
color1 #0D0D5A
color2 #111172
color3 #151589
color4 #888814
color5 #A9A919
color6 #E1E121
color7 #E7E7E7
color8 #A2A2A1
color9 #0D0D5A
color10 #111172
color11 #151589
color12 #888814
color13 #A9A919
color14 #E1E121
color15 #E7E7E7

mark1_foreground #E1E11A
mark2_foreground #E7B9B9
mark3_foreground #E1E11A
