cursor #6f87a4
cursor_text_color #ffffff

foreground            #b0c9e8
background            #000713
selection_foreground  #6f87a4
selection_background  #bec7d5
url_color             #d7e7ff

color0 #000713
color1 #debce1
color2 #324a64
color3 #d7e7ff
color4 #94acca
color5 #0a263e
color6 #6f87a4
color7 #6f87a4
color8 #a2abb8
color9 #b0c9e8
color10 #e3e2e4
color11 #ffffff
color12 #6f87a4
color13 #a7aab1
color14 #ced1d9
color15 #b0c9e8
