@define-color blur_background8 alpha(rgba(18, 19, 21, 1), 0.8);
    @define-color primary #d7e7ff;
    @define-color primary_container #94acca;
    @define-color primary_fixed #d0e4ff;
    @define-color primary_fixed_dim #b0c9e8;
