
$background = rgba(121315ff)

$error = rgba(ffdfdbff)

$error_container = rgba(ff877bff)

$inverse_on_surface = rgba(010102ff)

$inverse_primary = rgba(324a64ff)

$inverse_surface = rgba(e3e2e4ff)

$on_background = rgba(e3e2e4ff)

$on_error = rgba(190000ff)

$on_error_container = rgba(000000ff)

$on_primary = rgba(000713ff)

$on_primary_container = rgba(000000ff)

$on_primary_fixed = rgba(000000ff)

$on_primary_fixed_variant = rgba(0a263eff)

$on_secondary = rgba(010710ff)

$on_secondary_container = rgba(000000ff)

$on_secondary_fixed = rgba(000000ff)

$on_secondary_fixed_variant = rgba(1c252fff)

$on_surface = rgba(ffffffff)

$on_surface_variant = rgba(ffffffff)

$on_tertiary = rgba(110118ff)

$on_tertiary_container = rgba(000000ff)

$on_tertiary_fixed = rgba(000000ff)

$on_tertiary_fixed_variant = rgba(321c38ff)

$outline = rgba(ced1d9ff)

$outline_variant = rgba(a7aab1ff)

$primary = rgba(d7e7ffff)

$primary_container = rgba(94accaff)

$primary_fixed = rgba(d0e4ffff)

$primary_fixed_dim = rgba(b0c9e8ff)

$scrim = rgba(000000ff)

$secondary = rgba(dee6f5ff)

$secondary_container = rgba(a2abb8ff)

$secondary_fixed = rgba(dae3f1ff)

$secondary_fixed_dim = rgba(bec7d5ff)

$shadow = rgba(000000ff)

$source_color = rgba(6f87a4ff)

$surface = rgba(121315ff)

$surface_bright = rgba(494a4cff)

$surface_container = rgba(2b2c2eff)

$surface_container_high = rgba(363739ff)

$surface_container_highest = rgba(414244ff)

$surface_container_low = rgba(1e1f21ff)

$surface_container_lowest = rgba(030405ff)

$surface_dim = rgba(121315ff)

$surface_tint = rgba(b0c9e8ff)

$surface_variant = rgba(43474dff)

$tertiary = rgba(fddbffff)

$tertiary_container = rgba(c09fc3ff)

$tertiary_fixed = rgba(fbd7fdff)

$tertiary_fixed_dim = rgba(debce1ff)
